Title: Paveel's TIS page

description: "Software engineer at Qaiwan international university (QIU)

show_downloads: True
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme 
theme : jekyll-theme-modernist
